version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend:latest
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"
    networks:
      - backend-network
    secrets:
      - db_password
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend:latest
    env_file:
      - ./frontend/.env
    networks:
      - frontend-network
    ports:
      - "8080:80"
    configs:
      - source: nginx_conf
        target: /etc/nginx/conf.d/default.conf
    volumes:
      - ./frontend:/app
      - /app/node_modules
  db:
    image: postgres:14
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - ./db.env
    networks:
      - backend-network
    secrets:
      - db_password

networks:
  backend-network:
  frontend-network:

volumes:
  db-data:

configs:
  nginx_conf:
    file: ./frontend/nginx.conf

secrets:
  db_password:
    file: ./secrets/db_password.txt